### ISSUE TITLE
it seems he owners username has changed and now everything is broken.

### ISSUE THREAD

**Issue by apprehensivetarget** [Eren5960/EssentialsGO#2]

**Comment by xerenahmed** [comment]
feel free for open PR

**Comment by apprehensivetarget** [comment]
Sorry but i qouldnt know what to change

**Comment by xerenahmed** [comment]
Fixed via https://github.com/xerenahmed/EssentialsGO/commit/6ad188d07e7cd601ba9d59490d20c47010585669
